### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by the-redshift** [Invoice-Generator/invoice-generator-api#55]
Awesome stuff you built there!

Close at will.

**Comment by cohml** [comment]
While I generally agree with this sentiment (though I personally wouldn't clutter the issues with it since even after closing this issue will live on forever), the fact that nearly a year later it's still open indicates the project is basically stagnant.

Too bad as so many opportunities for improvement still remain!

**Comment by jaredtking** [comment]
Thank you!
