### ISSUE TITLE
Inconsistent Subtotal Rounding

### ISSUE THREAD

**Issue by forddavis** [Invoice-Generator/invoice-generator-api#64]
![Screenshot 2024-02-16 at 12 19 02 PM](https://github.com/Invoice-Generator/invoice-generator-api/assets/6877957/1a56b3f2-f1d8-449c-8889-09e0a9238867)

The values in Excel add up to 2,475.0000 and in the online editor they add up to $2,475.00 but when saved to PDF it gets rounded down to $2,474.99.

**Comment by 1fallxbamba** [comment]
I'm having the same issue with my invoices. Would be good to share the way their make their calculations

**Comment by jaredtking** [comment]
Can you please post the API request that reproduces this issue?

**Comment by jaredtking** [comment]
Rounding is applied after the calculation of each line item total (unit cost x quantity). Next the rounded line item totals are added together to produce the total. The correct total of your example should be 212399. I suspect that your amount paid calculation is not producing the correct total.

Although the UI for creating an invoice is not correctly generating the correct total until you download the invoice. I'm not sure if that was the issue you wanted to point out.

**Comment by 1fallxbamba** [comment]
Oh okay i see now. Yes i think that's the issue i was pointing out.

The way i'm calculating it (amountPaid) is :

- calculation of each line item total (unit_cost * quantity)
- the sum of item totals
- then i multiply it by 1.18 (to apply 18% VAT), which produces 212400

Can we know which rounding strategy you are using ? (in TS/JS)

**Comment by jaredtking** [comment]
After you calculate the line item total, you need to round the line item total before you add it to the invoice subtotal. Otherwise I think you have it correct. Thank you for your questions!

**Comment by 1fallxbamba** [comment]
Wonderful, thank you for you time !

**Comment by forddavis** [comment]
Does it really make sense to ignore fractional cents? I would think the total amount should be the exact total rounded to nearest cent. Not that the actual value matters, but if I bill 30 hours at $110 per hour it doesn't seem like it should come down to 3299.99 just because of the way the time was entered.

**Comment by 1fallxbamba** [comment]
True, that's exactly what i was thinking, it may produce wrong/doubtful invoices and confuse customers

**Comment by jaredtking** [comment]
What you are proposing to perform rounding only at the end is a valid way to handle rounding, however, the way it's implemented on Invoice-Generator.com is a different approach. It's not that fractional cents are ignored. Rounding is applied to each line item total after the line item total is calculated and before adding to the subtotal. As a result, the display of the rendered PDF (which does not display fractional cents in line item totals) is more consistent to a viewer. Otherwise they might add up the numbers and it would appear that the subtotal is off by one cent.

There was an issue where the web UI would apply rounding in a different place which has now been fixed.
